### ISSUE TITLE
createBunWsHandler handleRequest race problem

### ISSUE THREAD

**Issue by motopods-lucas** [cah4a/trpc-bun-adapter#11]
websocket

-----> open

https://github.com/cah4a/trpc-bun-adapter/blob/4de96b72e099c4d19561651bc43b74c8fc3240ec/src/createBunWSHandler.ts#L79
`await ctxPromise; // if this takes some time.`

----> message 
https://github.com/cah4a/trpc-bun-adapter/blob/4de96b72e099c4d19561651bc43b74c8fc3240ec/src/createBunWSHandler.ts#L290
```
    const promises = msgs
        .map((raw) =>
            parseTRPCMessage(raw, router._def._config.transformer),
        )
        .map(client.data.handleRequest); // client.data.handleRequest is no ready yet, so there is an error TypeError: Array.prototype.map callback must be a function.
```
https://github.com/cah4a/trpc-bun-adapter/blob/4de96b72e099c4d19561651bc43b74c8fc3240ec/src/createBunWSHandler.ts#L125
`client.data.handleRequest = ... // set  handleRequest `

**Comment by motopods-lucas** [comment]
Make a PR https://github.com/cah4a/trpc-bun-adapter/pull/12

**Comment by cah4a** [comment]
Thanks for your contributing!

Packaged version 1.2.0 is available now.

There more fixes, please double check on your case and re-open issue if reproduces.
