### ISSUE TITLE
Documentation: setting-up CORS

### ISSUE THREAD

**Issue by selcuk-sahin** [cah4a/trpc-bun-adapter#2]
Hi, 
I'm new to trpc and I couldn't set up CORS in server.ts

Is there a possiblity to add this into documentation? 

I was reading the [documentation on cors](https://trpc.io/docs/client/cors). It mentions that:
"You also need to enable CORS on your server by modifying your [adapter](https://trpc.io/docs/server/adapters), or the HTTP server which fronts your API. The best way to do this varies adapter-by-adapter and based on your hosting infrastructure, and individual adapters generally document this process where applicable."

Thanks,

**Comment by selcuk-sahin** [comment]
Although probably not an optimal one, 
I ended up using this solution which solved the CORS problem on my application.

```typescript
    Bun.serve(
        createBunServeHandler(
            {
                router: appRouter,
                /** enable CORS */
                responseMeta(opts) {
                    return {
                        status: 200,
                        headers: {
                            'Access-Control-Allow-Origin': '*',
                            'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
                            'Access-Control-Allow-Headers': 'Content-Type, Authorization',
                        }
                    }
                },
            },
        )
    )
```

**Comment by cah4a** [comment]
Added
