### ISSUE TITLE
Support `resHeaders` in context

### ISSUE THREAD

**Issue by ceopaludetto** [cah4a/trpc-bun-adapter#5]
`@trpc/server/adapters/fetch` recently added support to `resHeaders` in the context, this allow adding headers to the response inside query or mutations, since the createContext is just forwarded to the `fetchRequestHandler` I don't see any problem if we support as well. Actually we just need to change the `CreateBunContextOptions` with the `FetchCreateContextFnOptions` imported from `@trpc/server/adapters/fetch`. I've patched locally and everything works flawlessly

**Comment by cah4a** [comment]
Hey @ceopaludetto,
Yeah, that's really helpful feature and bun adapter should definitely have it.

Would love to incorporate this enhancement. 
Could you please open a Pull Request (PR) with your changes?
I'll publish a version.

Thank you for your contribution!

**Comment by ceopaludetto** [comment]
Hi, I've opened the [PR](https://github.com/cah4a/trpc-bun-adapter/pull/6), thank you
