### ISSUE TITLE
Types mismatches for tRPC +11.0.0-rc455

### ISSUE THREAD

**Issue by lunacrafts** [cah4a/trpc-bun-adapter#7]
Hey guys, thanks for creating and maintaining this package.

I'm having following typescript errors for the latest trpc version
  '@trpc/client': 11.0.0-rc.466
  '@trpc/server': 11.0.0-rc.466

but I recall it don't work for last at least two weeks.

Argument of type '{ endpoint: string; router: BuiltRouter<{ ctx: object; meta: object; errorShape: DefaultErrorShape; transformer: false; }, { ping: QueryProcedure<{ input: void; output: string; }>; subscribe: SubscriptionProcedure<...>; }>; }' is not assignable to parameter of type 'BunHttpHandlerOptions<BuiltRouter<{ ctx: object; meta: object; errorShape: DefaultErrorShape; transformer: false; }, { ping: QueryProcedure<{ input: void; output: string; }>; subscribe: SubscriptionProcedure<...>; }>>'.
  Property 'req' is missing in type '{ endpoint: string; router: BuiltRouter<{ ctx: object; meta: object; errorShape: DefaultErrorShape; transformer: false; }, { ping: QueryProcedure<{ input: void; output: string; }>; subscribe: SubscriptionProcedure<...>; }>; }' but required in type '{ req: Request; endpoint: string; }'.ts(2345)

**Comment by cah4a** [comment]
Hey @lunacrafts,

Thanks you for contribution and patience.
I've fixed typings and publish package version 1.1.2.

**Comment by lunacrafts** [comment]
Let's gooo! Thank you! 🥳
